import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/appComponents/Header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Section2Layout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={` ${inter.variable} antialiased`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
