
// Subscription tiers
export const SubscriptionPlans = {
    FREE: {
        name: "Free",
        price: 0,
        codeBlocks: 3,
        maxCodeLines: 160,
        descriptionLimit: 1000,
        commentLength: 1400,
        privateSnippets: 0,
        folders: 0,
        premiumTemplates: false,
        artboards: 5,
        designElements: 20,
        exportFormat: ["png","jpg"],
        exportAllArtboardAsPng: false,
        exportAllArtboardAsSvg: false,
        exportAllArtboardAsPdf: false,
        canPublish: false,
    },
    PRO: {
        name: "Pro",
        price: 3.99,
        codeBlocks: 6,
        maxCodeLines: 320,
        descriptionLimit: 3000,
        commentLength: 2400,
        privateSnippets: 15,
        folders: 5,
        premiumTemplates: true,
        artboards: 15,
        designElements: 50,
        exportFormat: ["png","jpg","svg","pdf"],
        exportAllArtboardAsPng: true,
        exportAllArtboardAsSvg: false,
        exportAllArtboardAsPdf: false,
        canPublish: false,
    },
    ELITE: {
        name: "Elite",
        price: 10,
        codeBlocks: 10,
        maxCodeLines: 640,
        descriptionLimit: 6000,
        commentLength: 5000,
        privateSnippets: Infinity,
        folders: Infinity,
        premiumTemplates: true,
        artboards: Infinity,
        designElements: Infinity,
        exportFormat: ["png","jpg","svg","pdf"],
        exportAllArtboardAsPng: true,
        exportAllArtboardAsSvg: true,
        exportAllArtboardAsPdf: true,
        canPublish: true,
    },
};